src/backend/controller/user.go, src/backend/controller/wishlist.go, src/backend/db/migrations/000002_create_wishlists_table.down.sql, src/backend/db/migrations/000002_create_wishlists_table.up.sql, src/backend/main.go, src/backend/model/wishlist.go, src/backend/repository/impl/wishlist.go, src/backend/repository/wishlist.go, src/backend/service/impl/wishlist.go, src/backend/service/wishlist.go
=> Реализован API для работы с Wish-листами

.github/workflows/test-deploy.yml
=> Настроено обновление тестового стенда

src/backend/db/migrations/000003_add_wish_table.down.sql, src/backend/db/migrations/000003_add_wish_table.up.sql
=> Добавлены миграции для таблицы желаний

docker-compose.dev.yml, docker-compose.yml, example.env
Исправлены замечания по ports и volumes
=> Исправлены замечания по https://github.com/stas12312/wishlists/issues/26

docker-compose.dev.yml, docker-compose.yml, example.env
=> Реализован проброс переменных окружений

src/backend/model/wishlist.go, src/backend/repository/impl/wishlist.go
=> Добавлено поле с количеством желаний для вишлистов

docker-compose.dev.yml, docker-compose.yml, example.env, src/backend/config/config.go, src/backend/db/migrate.go, src/backend/main.go
=> Изменены переменные окружения для подключения к БД

docker-compose.dev.yml, docker-compose.yml
=> Исправлено значение POSTGRES_USER

src/backend/controller/wishlist.go, src/backend/repository/impl/wishlist.go, src/backend/service/impl/wishlist.go, src/backend/service/impl/wishlist_test.go
=> Исправлено обновление вишлиста

example.env
=> Добавлен пример настройки для SMTP

.gitignore, docker-compose.dev.yml, docker-compose.yml, example.env
=> Доработаны docker-compose файлы

.github/workflows/go.yml, src/backend/Dockerfile
=> Go обновлен до версии 1.22

src/backend/error/code.go, src/backend/error/error.go, src/backend/error/handler.go, src/backend/main.go, src/backend/model/request.go
=> Реализован кастомный обработчик ошибок

src/backend/controller/user.go, src/backend/error/code.go, src/backend/model/code.go, src/backend/repository/code.go, src/backend/repository/impl/code.go, src/backend/repository/mocks/CodeRepository.go, src/backend/service/impl/user.go, src/backend/service/impl/user_test.go, src/backend/service/mocks/UserService.go, src/backend/service/user.go
=> Реализовано ограниченное количество попыток для проверки кода

src/backend/controller/user.go, src/backend/service/impl/user.go, src/backend/service/impl/user_test.go, src/backend/service/mocks/UserService.go, src/backend/service/user.go
=> Возвращение пары токенов при подтверждении email по ссылке

src/backend/controller/user.go, src/backend/controller/user_test.go, src/backend/controller/validate.go, src/backend/model/request.go, src/backend/model/user.go, src/backend/service/impl/user.go, src/backend/service/impl/user_test.go, src/backend/service/mocks/UserService.go, src/backend/service/user.go
=> Добавлена валидация для пароля

src/backend/controller/validate.go, src/backend/controller/wishlist.go, src/backend/db/migrations/000005_add_private_field_for_wishlists.down.sql, src/backend/db/migrations/000005_add_private_field_for_wishlists.up.sql, src/backend/model/wishlist.go, src/backend/repository/impl/wishlist.go
=> Реализована настройка доступности вишлиста

src/backend/controller/image.go, src/backend/controller/user.go, src/backend/controller/wishlist.go, src/backend/error/code.go, src/backend/middleware/auth.go, src/backend/service/impl/wishlist.go, src/backend/service/impl/wishlist_test.go
=> Реализована возможность получать вишлисты без авторизации [API]

src/backend/service/impl/user.go, src/backend/service/impl/user_test.go
=> Исправлена проверка кода подтверждения [API]

src/frontend/src/App.tsx, src/frontend/src/pages/Profile.tsx
2.Исправлена ошибка с дублированием запросов
=> 1.Исправлена ошибка при подтверждении почты

src/backend/service/impl/user.go
=> [API] Исправлена проверка кода

src/frontend/src/pages/Welcome.tsx
=> [UI] Переадресация с главной страницы на страницу с вишлистами

src/backend/controller/user.go, src/backend/error/code.go, src/backend/service/impl/user.go, src/backend/service/impl/user_test.go, src/backend/service/mocks/UserService.go, src/backend/service/user.go
=> [API] Реализована смена пароля

src/backend/controller/user.go, src/backend/model/code.go
=> [API] Добавлен заголовок для получение всех данных кода

src/frontend/src/components/SignButton.tsx, src/frontend/src/models/IWish.ts, src/frontend/src/pages/Profile.tsx, src/frontend/src/pages/signIn/SignInForm.tsx, src/frontend/src/pages/wishlist/WishlistEditDialog.tsx, src/frontend/src/pages/wishlist/Wishlists.tsx, src/frontend/src/services/WishlistService.ts
https://github.com/stas12312/wishlists/issues/110
=> Добавлено поле Доступен в форму создания/редактирования вишлиста

src/frontend/src/pages/SignUp.tsx
https://github.com/stas12312/wishlists/issues/70
=> Убрано автозаполнение

src/frontend/src/pages/wishlist/Wishlists.tsx
https://github.com/stas12312/wishlists/issues/78
=> Исправлено отображение заголовка вишлиста

src/frontend/src/helpers/Functions.ts, src/frontend/src/models/IWish.ts, src/frontend/src/pages/wishlist/WishlistFooter.tsx, src/frontend/src/pages/wishlist/Wishlists.tsx
https://github.com/stas12312/wishlists/issues/31
=> На UI добавлено поле с количеством желаний

src/frontend/src/pages/SignUp.tsx, src/frontend/src/pages/signIn/PasswordRestore.tsx, src/frontend/src/services/AuthService.ts, src/frontend/src/store/store.ts
https://github.com/stas12312/wishlists/issues/133
=> Исправлены ошибки в местах использования кодов подтверждения

src/backend/mail/impl/smtp.go
=> [API] Реализована асинхронная отправка письма на почту

src/backend/config/config.go, src/backend/controller/user.go, src/backend/main.go
=> [Backend] Реализована возможность профилирования

src/backend/controller/user.go, src/backend/service/impl/user.go
=> [API] Исправлен формат ошибки при восстановлении пароля

src/backend/controller/wishlist.go, src/backend/repository/impl/wish.go, src/backend/service/impl/wishlist.go, src/backend/service/wishlist.go
=> [API] Добавлено API для получения желания

src/frontend/app/layout.tsx, src/frontend/components/wishlist/list.tsx
=> [UI] Исправлено отображение меню на мобильном устройстве

src/frontend/app/layout.tsx, src/frontend/app/login/auth.ts, src/frontend/app/login/page.tsx, src/frontend/app/register/page.tsx, src/frontend/components/user.tsx, src/frontend/components/wish/card.tsx, src/frontend/components/wish/form.tsx, src/frontend/components/wish/saveModal.tsx, src/frontend/components/wishlist/card.tsx, src/frontend/components/wishlist/form.tsx, src/frontend/components/wishlist/saveModal.tsx, src/frontend/components/wishlistDetail.tsx, src/frontend/lib/auth.ts, src/frontend/lib/requests.ts, src/frontend/tailwind.config.js
* Исправлен размер шрифта для мобильных устройств
* Удалены лишние console.log
* Исправлены заголовки модальных окон
#Resolve 156
=> [UI] Доработан интерфейс:

src/frontend/.gitignore, src/frontend/app/layout.tsx, src/frontend/components/user.tsx, src/frontend/components/wish/card.tsx, src/frontend/components/wishlistDetail.tsx, src/frontend/lib/requests.ts, src/frontend/middleware.ts, src/frontend/package.json, src/frontend/store/userStore.ts
=> [UI] Добавлен режим просмотра списка желания

src/frontend/app/login/page.tsx, src/frontend/app/register/page.tsx, src/frontend/app/restore-password/page.tsx, src/frontend/lib/auth.ts, src/frontend/lib/requests.ts, src/frontend/middleware.ts
=> [UI] Добавлена форма восстановления пароля

src/frontend/app/auth/confirm/page.tsx, src/frontend/app/auth/login/page.tsx, src/frontend/app/auth/reset-password/page.tsx
=> [UI] Исправлено расположение useEffect

src/frontend/app/auth/login/page.tsx, src/frontend/app/auth/register/page.tsx, src/frontend/app/auth/reset-password/page.tsx, src/frontend/components/passwordInput.tsx
=> [UI] Добавлен компонент для ввода пароля

src/frontend/app/auth/register/page.tsx
=> [UI] Исправлена ошибка в page.tsx

src/frontend/app/auth/confirm/page.tsx, src/frontend/app/auth/login/auth.ts, src/frontend/app/auth/login/page.tsx, src/frontend/app/auth/register/page.tsx, src/frontend/app/auth/reset-password/page.tsx, src/frontend/app/layout.tsx, src/frontend/app/settings/page.tsx, src/frontend/app/wishlists/[uuid]/page.tsx, src/frontend/components/menu.tsx, src/frontend/components/passwordInput.tsx, src/frontend/components/themeSwitcher.tsx, src/frontend/components/user.tsx, src/frontend/components/wish/card.tsx, src/frontend/components/wish/form.tsx, src/frontend/components/wish/saveModal.tsx, src/frontend/components/wishlist/card.tsx, src/frontend/components/wishlist/form.tsx, src/frontend/components/wishlist/list.tsx, src/frontend/components/wishlist/saveModal.tsx, src/frontend/components/wishlistDetail.tsx, src/frontend/config/site.ts, src/frontend/eslint.config.mjs, src/frontend/lib/auth.ts, src/frontend/lib/models.ts, src/frontend/lib/requests.ts, src/frontend/middleware.ts, src/frontend/store/userStore.ts
=> [UI] Исправлены замечания eslint

src/frontend/app/auth/login/auth.ts, src/frontend/app/auth/login/page.tsx, src/frontend/eslint.config.mjs
=> [UI] Добавлена обработка ошибок на странице авторизации

src/frontend/components/uploadButton.tsx, src/frontend/components/wish/form.tsx, src/frontend/lib/auth.ts, src/frontend/lib/requests.ts, src/frontend/middleware.ts
=> [UI] Добавлена загрузка изображения

src/frontend/app/auth/confirm/page.tsx, src/frontend/app/auth/reset-password/page.tsx
=> [UI] Исправлено использование useSearchParams

src/frontend/components/uploadButton.tsx, src/frontend/components/wish/form.tsx
=> [UI] Добавлена проверка на загружаемый файл

src/frontend/components/wishlist/list.tsx, src/frontend/components/wishlistDetail.tsx
=> [UI] Добавлен toast при удалении вишлиста/желания

src/frontend/app/(root)/layout.tsx, src/frontend/app/(root)/settings/page.tsx, src/frontend/components/menu.tsx, src/frontend/components/themeSwitcher.tsx, src/frontend/components/user.tsx
=> [UI] Изменено расположение переключателя темы

.github/workflows/test-deploy.yml, src/frontend/Dockerfile, src/frontend/app/(root)/layout.tsx, src/frontend/app/layout.tsx, src/frontend/components/themeSwitcher.tsx, src/frontend/lib/requests.ts, src/frontend/package.json
=> [UI] Добавлено отображение версии

.github/workflows/test-deploy.yml
=> [CI/CD] Исправлена конфигурация

docker-compose.dev.yml, src/frontend/Dockerfile
=> [CI/CD] Исправлено проставление версии UI

src/frontend/app/(root)/layout.tsx, src/frontend/components/version.tsx
=> [UI] Реализовано фиксирование левого меню

.github/workflows/test-deploy.yml
=> [CI/CD] Исправлена дата сборки

src/frontend/app/auth/register/page.tsx, src/frontend/app/auth/reset-password/page.tsx, src/frontend/components/codeInput.tsx, src/frontend/lib/requests.ts, src/frontend/package.json, src/frontend/styles/globals.css
=> [UI] Добавлен компонент для ввода кодов

src/frontend/components/wishlist/card.tsx, src/frontend/components/wishlistDetail.tsx
=> [UI] Добавлено редактирование/удаление на страницу вишлиста

src/frontend/app/auth/login/page.tsx, src/frontend/app/auth/oauth/[type]/route.ts, src/frontend/lib/models.ts, src/frontend/lib/requests.ts
=> [UI] Добавлена авторизация через соц сети

src/frontend/app/(root)/layout.tsx, src/frontend/components/wishlist/card.tsx, src/frontend/components/wishlist/form.tsx, src/frontend/components/wishlistDetail.tsx
=> [UI] Исправлено отображение действий в вишлисте в режиме просмотра

src/frontend/components/confirmation.tsx, src/frontend/components/wish/card.tsx, src/frontend/components/wishlist/card.tsx
=> [UI] Добавлено подтверждение действия при удалении

src/frontend/components/AddCardButton.tsx, src/frontend/components/wishlist/list.tsx, src/frontend/components/wishlistDetail.tsx
=> [UI] Изменена кнопка для добавления вишлиста/желания

src/backend/repository/impl/wish.go, src/backend/repository/impl/wishlist.go
=> [API] Реализовано полное удаление вишлиста/желания

src/frontend/components/wishlist/card.tsx, src/frontend/components/wishlist/list.tsx, src/frontend/lib/requests.ts
=> [UI] Реализовано восстановление вишлиста

src/backend/repository/impl/wishlist.go
=> [API] Доработана сортировка вишлистов

src/backend/controller/wishlist.go, src/backend/db/migrations/000007_add_presenter_user_id.down.sql, src/backend/db/migrations/000007_add_presenter_user_id.up.sql, src/backend/error/code.go, src/backend/model/null.go, src/backend/model/wish.go, src/backend/repository/impl/wish.go, src/backend/repository/mocks/WishRepository.go, src/backend/repository/wish.go, src/backend/service/impl/wishlist.go, src/backend/service/wishlist.go
=> [API] Реализовано бронирование желания

src/backend/repository/impl/wish.go
=> [API] Исправлено поле is_reserved

src/backend/repository/impl/wish.go
=> [API] Исправлена сортировка желаний

src/frontend/app/(root)/wishes/page.tsx, src/frontend/components/menu.tsx, src/frontend/components/reserved/reservedList.tsx, src/frontend/components/wish/card.tsx, src/frontend/components/wishlistDetail.tsx, src/frontend/lib/models.ts, src/frontend/lib/requests.ts
=> [UI] Реализовано бронирование желаний

src/frontend/components/wishlist/form.tsx, src/frontend/components/wishlistDetail.tsx
=> [UI] Исправлено отображение даты на странице вишлиста

src/frontend/components/wish/card.tsx
=> [UI] Исправлено отображение бронирования вишлиста

src/backend/model/wish.go, src/backend/service/impl/wishlist.go, src/backend/service/impl/wishlist_test.go
=> [API] Реализовано получение допустимых действий для желаний

src/backend/service/impl/wishlist.go, src/backend/service/impl/wishlist_test.go
=> [API] Исправлены действия при получении желания

src/frontend/components/reserved/reservedList.tsx, src/frontend/components/wish/card.tsx, src/frontend/lib/models.ts
=> [UI] Доработано бронирование желания

src/backend/repository/impl/wishlist.go
=> [API] Исправлено вычисление количества желаний для вишлиста

src/frontend/components/wishlist/card.tsx, src/frontend/lib/label.ts
=> [UI] Добавлено количества желаний

src/backend/controller/wishlist.go, src/backend/model/wishlist.go, src/backend/repository/impl/wishlist.go, src/backend/repository/wishlist.go
=> [API] Реализован фильтр по автору вишлиста

src/frontend/components/filter.tsx, src/frontend/components/wish/card.tsx, src/frontend/components/wishlist/list.tsx, src/frontend/lib/requests.ts
=> [UI] Добавлен фильтр по пользователю при получении вишлиста

src/backend/controller/user.go
=> [API] Реализовано получение пользователя по идентификатору

src/frontend/app/(root)/users/[id]/page.tsx, src/frontend/components/pageSpinner.tsx, src/frontend/components/user.tsx, src/frontend/components/userPage.tsx, src/frontend/components/wishlist/card.tsx, src/frontend/components/wishlist/list.tsx, src/frontend/components/wishlistDetail.tsx, src/frontend/lib/requests.ts, src/frontend/middleware.ts
=> [UI] Реализована страница пользователя

src/frontend/app/(root)/settings/page.tsx, src/frontend/components/menu.tsx, src/frontend/components/wishlist/card.tsx
=> [UI] Добавлено копирование ссылки на профиль в настройки

src/frontend/app/(root)/settings/page.tsx, src/frontend/app/(root)/users/[id]/page.tsx, src/frontend/app/(root)/users/[username]/page.tsx, src/frontend/components/user.tsx, src/frontend/components/userPage.tsx, src/frontend/lib/models.ts, src/frontend/lib/requests.ts, src/frontend/store/userStore.ts
=> [UI] Поиск по идентификатору изменен на поиск по имени пользователя

src/frontend/app/(root)/settings/page.tsx, src/frontend/components/user.tsx, src/frontend/lib/requests.ts, src/frontend/package.json, src/frontend/store/userStore.ts
=> [UI] Добавлено редактирование профиля

src/frontend/components/version.tsx
=> [UI] Убран префикс v при отображении версии

src/frontend/components/codeInput.tsx, src/frontend/components/reserved/reservedList.tsx, src/frontend/components/user.tsx, src/frontend/components/userPage.tsx, src/frontend/lib/requests.ts, src/frontend/middleware.ts
=> [UI] Исправлено формирование ссылки

src/frontend/app/(root)/page.tsx, src/frontend/components/landing.tsx, src/frontend/lib/auth.ts, src/frontend/middleware.ts
=> [UI] Добавлена главная страница

src/backend/oauth/yandex/yandex.go, src/backend/repository/impl/user.go, src/backend/repository/mocks/UserRepository.go, src/backend/repository/user.go, src/backend/service/impl/user.go
=> [API] Добавлена загрузка изображения профиля через OAuth

src/backend/main.go, src/backend/model/wishlist.go, src/backend/service/impl/wishlist.go, src/backend/service/impl/wishlist_test.go
=> [API] Добавлена информация о пользователе при получении вишлиста

src/frontend/components/userPage.tsx, src/frontend/components/wishlistDetail.tsx, src/frontend/lib/models.ts
=> [UI] Доработано отображение вишлиста

src/backend/controller/wishlist.go, src/backend/repository/impl/wish.go, src/backend/repository/mocks/WishRepository.go, src/backend/repository/wish.go, src/backend/service/impl/wishlist.go, src/backend/service/wishlist.go
=> [API] Реализована возможность пометить желание исполненным

src/frontend/components/wish/card.tsx, src/frontend/components/wish/card_menu.tsx, src/frontend/lib/models.ts, src/frontend/lib/requests.ts
=> [UI] Реализована возможность помечать желания исполненными

src/backend/Dockerfile, src/backend/controller/friends.go, src/backend/db/migrations/000009_add_friends_tables.down.sql, src/backend/db/migrations/000009_add_friends_tables.up.sql, src/backend/main.go, src/backend/model/friend.go, src/backend/model/user.go, src/backend/repository/friend.go, src/backend/repository/impl/friend.go, src/backend/service/friend.go, src/backend/service/impl/friend.go, src/backend/service/impl/user_test.go, src/backend/uof/impl/uof_postgres.go, src/backend/uof/uof.go
=> [API] Реализованы методы для функционала друзей

src/frontend/app/(root)/friends/page.tsx, src/frontend/components/confirmation.tsx, src/frontend/components/friends/list.tsx, src/frontend/components/friends/requests.tsx, src/frontend/components/menu.tsx, src/frontend/components/userPage.tsx, src/frontend/components/wish/card.tsx, src/frontend/lib/label.ts, src/frontend/lib/models.ts, src/frontend/lib/requests.ts, src/frontend/package.json, src/frontend/store/counterStore.ts
=> [UI] Реализована страница "Друзья"

src/frontend/app/(root)/friends/page.tsx, src/frontend/components/menu.tsx
=> [UI] Исправлено отображение счетчиков

src/backend/controller/wishlist.go, src/backend/model/navigation.go, src/backend/model/request.go, src/backend/repository/impl/wishlist.go, src/backend/repository/mocks/WishlistRepository.go, src/backend/repository/wishlist.go, src/backend/service/impl/wishlist.go, src/backend/service/impl/wishlist_test.go, src/backend/service/wishlist.go
=> [API] Реализована навигация по курсору

src/frontend/app/layout.tsx, src/frontend/components/friends/requests.tsx, src/frontend/components/wishlist/card.tsx, src/frontend/components/wishlist/list.tsx, src/frontend/lib/models.ts, src/frontend/lib/requests.ts, src/frontend/store/userStore.ts
=> [UI] Добавлена курсорная навигация

src/frontend/app/(root)/page.tsx, src/frontend/components/userPage.tsx, src/frontend/components/wishlist/card.tsx, src/frontend/components/wishlist/form.tsx, src/frontend/components/wishlist/list.tsx, src/frontend/components/wishlist/saveModal.tsx, src/frontend/components/wishlistDetail.tsx, src/frontend/lib/auth.ts, src/frontend/lib/models.ts, src/frontend/lib/models/token.tsx, src/frontend/lib/models/wishlist.tsx, src/frontend/lib/requests.ts
=> [UI] Переработан компонент списка вишлистов

src/frontend/app/(root)/friends/page.tsx, src/frontend/app/(root)/settings/page.tsx, src/frontend/components/friends/list.tsx, src/frontend/components/friends/requests.tsx, src/frontend/lib/label.ts
=> [UI] Добавлена ссылка для друзей на страницу "Друзья"

src/frontend/components/visibleIcon.tsx, src/frontend/components/wishlist/form.tsx
=> [UI] Добавлена настройка видимости вишлиста "Друзьям"

src/backend/model/wishlist.go
=> [API] Исправлена валидация на пустое название вишлиста

src/frontend/Dockerfile
=> [UI] Добавлен package-lock.json в сборку образа

src/backend/model/wishlist.go, src/backend/service/impl/wishlist.go
=> [API] Исправлено получение вишлиста, доступный друзьям

.github/workflows/eslint.yml, .github/workflows/go.yml
=> [CI/CD] Отключен запуск тестов при пуше в main

src/frontend/components/wish/card.tsx
=> [UI] Добавлена заглушка при отсутствии изображения у желания

src/frontend/components/reserved/reservedList.tsx
=> [UI] Добавлена заглушка при отсутствии забронированных желаний

src/backend/model/wish.go, src/backend/model/wishlist.go, src/backend/repository/impl/wish.go
=> [API] Добавлены поля для забронированных желаний

src/backend/model/wishlist.go, src/backend/repository/impl/wish.go
=> [API] Добавлена дата события для забронированных желаний

src/frontend/lib/models/user.tsx, src/frontend/lib/models/wish.tsx
=> [UI] Доработано отображение забронированных желаний

src/frontend/components/friends/list.tsx
=> [UI] Исправлены отступы в списке друзей

src/frontend/app/(root)/friends/page.tsx, src/frontend/app/(root)/page.tsx, src/frontend/app/(root)/settings/page.tsx, src/frontend/components/pageHeader.tsx, src/frontend/components/reserved/reservedList.tsx, src/frontend/components/wishlistDetail.tsx
=> [UI] Добавлен компонент для заголовка страницы

src/backend/repository/impl/wish.go
=> [API] Исправлено возвращение доступных действий при обновлении желания

src/backend/model/null.go
=> [API] Исправлена замена ковычек

src/frontend/components/desirability/index.tsx
=> [UI] Доработан компонент выбора желанности

src/frontend/components/visibleIcon.tsx, src/frontend/components/wishlist/form.tsx, src/frontend/lib/models/wishlist.tsx, src/frontend/lib/requests.ts
=> [UI] Добавлен выбор друзей, для которых доступен вишлиста

src/frontend/components/wishlist/form.tsx
=> [UI] Добавлен аватар пользователя в список выбранных пользователей

src/frontend/app/(root)/wishes/layout.tsx
=> [UI] Исправлено название страницы с забронированными желаниями

src/frontend/components/menu.tsx, src/frontend/store/userStore.ts
=> [UI] Исправлено удаление пользователя из UserStore после выхода

src/frontend/app/(root)/users/[username]/opengraph-image.tsx, src/frontend/app/(root)/wishlists/[uuid]/opengraph-image.tsx, src/frontend/app/opengraph-image.tsx, src/frontend/components/ogImage.tsx
=> [UI] Добавлена генерация OG:Image для основных страниц

src/frontend/components/ogImage.tsx, src/frontend/middleware.ts
=> [UI] Исправлено открытие opengraph-image без авторизации

src/frontend/app/layout.tsx, src/frontend/config/site.ts
=> [UI] Добавлены OG теги

src/frontend/app/sitemap.ts
=> [UI] Добавлен sitemap.xml

src/frontend/components/reserved/reservedList.tsx, src/frontend/components/userPage.tsx, src/frontend/components/wishlistDetail.tsx
=> [UI] Доработаны загрузки страниц

src/frontend/components/userPage.tsx
=> [UI] Исправлена загрузка вишлистов на странице пользователя

src/frontend/app/auth/login/auth.ts, src/frontend/lib/auth.ts
=> [UI] Увеличено время хранения токена в cookies

src/frontend/lib/auth.ts, src/frontend/middleware.ts
=> [UI] Исправлено обновление токена

src/frontend/app/(root)/wishlists/[uuid]/page.tsx, src/frontend/components/userPage.tsx, src/frontend/components/wishlist/detail.tsx, src/frontend/components/wishlist/filter.tsx, src/frontend/components/wishlist/list.tsx
=> [UI] Исправлено отображение пользователя

src/frontend/app/robots.ts
=> [UI] Добавлена генерация robots.txt

src/backend/model/user.go
=> [API] Исправлен получение пользователя

src/frontend/components/userPage.tsx, src/frontend/components/wishlist/detail.tsx
=> [UI] Доработан вид загрузки компонентов

src/backend/repository/impl/friend.go
=> [API] Исправлено получение заявок в друзья

src/frontend/components/friends/list.tsx, src/frontend/components/friends/menu.tsx, src/frontend/components/menu/trigger.tsx
=> [UI] Доработана карточка друга на странице "Друзья"

src/frontend/components/friends/list.tsx, src/frontend/components/wish/card.tsx, src/frontend/components/wishlist/card.tsx
=> [UI] Исправлено отсутствие анимации при нажатии на карточку

src/frontend/components/wishlist/list.tsx
=> [UI] Доработано отображение карточек вишлистов

src/frontend/app/(root)/settings/page.tsx, src/frontend/components/user.tsx
=> [UI] Добавлены кнопки выхода в настройки и профиль

src/frontend/components/menu.tsx
=> [UI] Доработано меню

src/frontend/app/(root)/layout.tsx
=> [UI] Исправлены отступы для футера

src/frontend/app/layout.tsx
=> [UI] Исправлено отображение toast-сообщения

src/frontend/app/(root)/settings/page.tsx
=> [UI] Исправлено отображение копирование ссылки на профиль

src/frontend/components/menu.tsx
=> [UI] Исправлен переход на страницу "Желания"

src/frontend/app/(root)/layout.tsx
=> [UI] Исправлено отображение меню для неавторизованного пользователя

src/backend/db/migrations/000013_update_user_indexes.down.sql, src/backend/db/migrations/000013_update_user_indexes.up.sql, src/backend/repository/impl/user.go
=> [API] Исправлен поиск по email и username с разными регистрами

src/frontend/components/menu.tsx
=> [UI] Изменена иконка для пунтка "Вишлисты"

src/frontend/components/userPage.tsx, src/frontend/components/wishlist/detail.tsx
=> [UI] Исправлено отображение заголовков страниц вишлистов

src/frontend/app/(root)/layout.tsx
=> [UI] Меню зафиксировано по ширине

src/frontend/Dockerfile
=> [CI/CD] Исправлен перенос public в образ UI

src/frontend/app/auth/register/page.tsx, src/frontend/app/auth/reset-password/page.tsx, src/frontend/components/menu.tsx, src/frontend/components/passwordInput.tsx
=> [UI] Исправлен ввод пароля

src/frontend/components/confirmation.tsx, src/frontend/components/friends/list.tsx
=> [UI] Исправлено удаление пользователя из друзей

src/frontend/components/settings/profile.tsx, src/frontend/components/uploadButton.tsx, src/frontend/next.config.js
=> [UI] Исправлено отображение ошибок при загрузке изображения

src/frontend/components/landing.tsx
=> [UI] Доработано отображения изображения

src/frontend/components/wish/form.tsx
=> [UI] Исправлена загрузка изображения для желания

src/frontend/app/(root)/layout.tsx, src/frontend/components/userPage.tsx, src/frontend/components/wishlist/detail.tsx
=> [UI] Исправлены отступы на мобильных устройствах

src/frontend/components/friends/requests.tsx
=> [UI] Изменено название кнопки для отмены заявки

src/frontend/components/friends/requests.tsx
=> [UI] Исправлены отступы в заявках в друзья

src/frontend/components/menu.tsx
=> [UI] Убрано выделение пунктов на мобильном меню

.github/workflows/release-deploy.yml, .github/workflows/test-deploy.yml, src/frontend/Dockerfile, src/frontend/app/layout.tsx, src/frontend/components/yandexMetrika.tsx
=> [UI] Добавлена Яндекс.Метрика

src/frontend/app/auth/login/page.tsx, src/frontend/app/auth/register/page.tsx, src/frontend/app/auth/reset-password/page.tsx, src/frontend/components/wish/form.tsx, src/frontend/components/wishlist/form.tsx, src/frontend/components/yandexMetrika.tsx
=> [UI] Добавлены идентификаторы и названия форм

src/backend/db/migrations/000013_update_user_indexes.down.sql, src/backend/db/migrations/000013_update_user_indexes.up.sql, src/backend/mail/client.go, src/backend/mail/impl/smtp.go, src/backend/mail/template/code.html, src/backend/repository/impl/user.go, src/backend/service/impl/user.go, src/backend/service/impl/user_test.go
=> [API] Доработана отправка письма с кодом подтверждения

src/backend/Dockerfile
=> [API] Исправлена загрузка шаблона письма

src/frontend/app/auth/login/layout.tsx, src/frontend/app/auth/login/page.tsx, src/frontend/app/auth/register/layout.tsx, src/frontend/config/site.ts
=> [UI] Исправлены заголовки страниц

src/frontend/app/manifest.ts
=> [UI] Добавлен manifest для PWA

src/backend/service/impl/wishlist.go, src/frontend/components/yandexMetrika.tsx
=> [API] Исправлено бронирование исполненных желаний

src/backend/repository/impl/wish.go, src/frontend/components/wish/card.tsx
=> [UI] Доработано отображение статусов брони/исполнения желания

src/backend/controller/user.go, src/backend/model/user.go, src/backend/service/impl/user.go
=> [API] Реализован метод для получения наличия пароля

src/frontend/app/(root)/settings/page.tsx, src/frontend/components/passwordInput.tsx, src/frontend/components/settings/item.tsx, src/frontend/components/settings/profile.tsx, src/frontend/components/settings/security.tsx, src/frontend/lib/models/user.tsx, src/frontend/lib/requests.ts, src/frontend/lib/requests/base.tsx, src/frontend/lib/requests/user.tsx
=> [UI] Добавлена секция безопасность в Настройки

src/frontend/app/(root)/settings/page.tsx, src/frontend/components/confirmation.tsx, src/frontend/components/settings/buttons.tsx, src/frontend/lib/requests/user.tsx
=> [UI] Добавлена возможность удалить аккаунт в настройках

src/frontend/app/auth/register/page.tsx, src/frontend/lib/models.ts
=> [UI] Добавлена возможность отправить письмо повторно

src/frontend/app/auth/register/page.tsx
=> [UI] Доработка кнопки обратного отсчета

src/frontend/components/wishlist/filter.tsx
=> [UI] Исправлен переключение фильтра на странице вишлистов

src/frontend/components/desirability/index.tsx, src/frontend/components/settings/buttons.tsx, src/frontend/components/wish/form.tsx, src/frontend/components/wishlist/form.tsx
=> [UI] Исправлена валидация форм добавления желания и вишлиста

src/frontend/components/wishlist/form.tsx
=> [UI] Исправлено удаление даты события

src/frontend/app/(root)/page.tsx, src/frontend/components/AddCardButton.tsx, src/frontend/components/wish/card.tsx, src/frontend/components/wish/cardImage.tsx, src/frontend/components/wishlist/detail.tsx, src/frontend/components/wishlist/list.tsx
=> [UI] Доработана страница вишлистов

src/frontend/components/confirmation.tsx
=> [UI] Исправлено центрирование заголовка окна подтверждения

src/frontend/components/wish/card.tsx, src/frontend/components/wish/cardImage.tsx, src/frontend/components/wish/fullCard.tsx
=> [UI] Доработано отображение пользователя в карточке вишлиста

src/frontend/components/uploadButton.tsx, src/frontend/components/user.tsx
=> [UI] Исправлено отображение аватара пользователя

src/frontend/components/wish/form.tsx, src/frontend/components/wish/fullCard.tsx, src/frontend/lib/url.ts
=> [UI] Добавлена проверка валидности ссылки

.github/workflows/release-deploy.yml, .github/workflows/test-deploy.yml, src/frontend/Dockerfile, src/frontend/components/marketIcon.tsx, src/frontend/components/wish/cardImage.tsx, src/frontend/components/wish/form.tsx, src/frontend/components/wish/fullCard.tsx, src/frontend/lib/url.ts
=> [UI] Добавлено отображение иконок магазинов

src/frontend/components/marketIcon.tsx, src/frontend/components/wish/form.tsx, src/frontend/components/wishlist/form.tsx
=> [UI] Добавлены кнопки для очистки полей форм желания/вишлиста

src/frontend/components/wishlist/form.tsx
=> [UI] Исправлено отображение года и месяца при выборе даты

src/frontend/components/wish/form.tsx
=> [UI] Исправлено очистка поля "Ссылка на изображение"

src/backend/repository/impl/image.go
=> [UI] Добавлен Cache-Control при отправке изображения в S3

src/frontend/app/auth/register/page.tsx
=> [UI] Добавлено пользовательское соглашение

src/frontend/Dockerfile, src/frontend/next.config.js
=> [CD/CD] Исправлен перенос next.config.js в Docker образ

src/frontend/components/landing.tsx
=> [UI] Доработана кнопка "Создать вишлист" на главной странице

src/frontend/components/friends/list.tsx, src/frontend/components/settings/profile.tsx, src/frontend/components/userPage.tsx, src/frontend/components/wishlist/detail.tsx, src/frontend/lib/user.ts
=> [UI] Добавлен @ перед имененм пользователя

src/backend/repository/impl/image.go
=> [API] Добавлена отправка Content-Type при загрузке в S3 хранилище

.github/workflows/release-deploy.yml, .github/workflows/test-deploy.yml, src/frontend/.gitignore, src/frontend/Dockerfile, src/frontend/app/(root)/friends/page.tsx, src/frontend/app/global-error.tsx, src/frontend/instrumentation.ts, src/frontend/next.config.js, src/frontend/package-lock.json, src/frontend/package.json, src/frontend/sentry.client.config.ts, src/frontend/sentry.edge.config.ts, src/frontend/sentry.server.config.ts
=> [UI] Настроен Sentry

src/frontend/app/auth/register/page.tsx
=> [UI] Исправлено позиционирование элементов

src/frontend/components/settings/profile.tsx, src/frontend/components/uploadButton.tsx, src/frontend/components/wish/form.tsx, src/frontend/lib/file.ts
=> [UI] Реализована вставка изображения из буфера

src/backend/controller/friends.go, src/backend/main.go, src/backend/service/mocks/FriendService.go
=> [API] Добавлены методы для получения списка друзей пользователя

src/frontend/components/wishlist/card.tsx, src/frontend/components/wishlist/detail.tsx, src/frontend/components/wishlist/list.tsx
=> [UI] Исправлено удаление вишлиста мимо архива

src/frontend/components/friends/list.tsx, src/frontend/lib/requests/user.tsx
=> [UI] Добавлено отображение ошибки на странице друзей

src/frontend/components/wish/cardImage.tsx
=> [UI] Добавлен фон для png изображений

src/backend/model/wishlist.go, src/backend/repository/impl/wishlist.go
=> [API] Добавлен фильтр для получение вишлистов по username

src/frontend/components/wishlist/form.tsx
=> [UI] Доработан выбор доступности вишлиста

src/frontend/components/wish/cardImage.tsx
=> [UI] Доработан градиент на карточке желания

src/frontend/lib/requests.ts
=> [UI] Исправлено получение вишлистов пользователя по username

src/frontend/components/wish/card.tsx, src/frontend/components/wishlist/card.tsx, src/frontend/components/wishlist/detail.tsx
=> [UI] Добавлены title для текстовых полей

src/frontend/components/wish/cardImage.tsx
=> [UI] Исправлено отображение изображения в желании

src/frontend/package-lock.json, src/frontend/package.json
=> [UI] Обновлен HeroUI

src/backend/controller/wishlist.go, src/backend/repository/impl/wish.go, src/backend/service/impl/wishlist.go, src/backend/service/wishlist.go
=> [API] Добавлен метод для переноса желания

src/frontend/components/wish/card.tsx, src/frontend/components/wish/form.tsx, src/frontend/components/wishlist/detail.tsx, src/frontend/components/wishlist/selectModal.tsx, src/frontend/lib/requests.ts, src/frontend/lib/requests/wish.tsx, src/frontend/lib/wish/menu.ts, src/frontend/package-lock.json, src/frontend/package.json
=> [UI] Реализован перенос желания в другой вишлист

src/backend/controller/wishlist.go
=> [API] Исправлено сообщение при открытии недоступного вишлиста

src/frontend/lib/wish/menu.ts
=> [UI] Измене порядок действий для желания

src/frontend/app/(root)/friends/page.tsx, src/frontend/app/auth/register/page.tsx, src/frontend/app/layout.tsx, src/frontend/app/providers.tsx, src/frontend/components/friends/list.tsx, src/frontend/components/friends/page.tsx, src/frontend/components/friends/requests.tsx, src/frontend/components/settings/buttons.tsx, src/frontend/components/settings/profile.tsx, src/frontend/components/settings/security.tsx, src/frontend/components/user.tsx, src/frontend/components/user/status.tsx, src/frontend/components/wish/card.tsx, src/frontend/components/wishlist/detail.tsx, src/frontend/components/wishlist/list.tsx, src/frontend/components/wishlist/menu.tsx, src/frontend/package-lock.json, src/frontend/package.json
=> [UI] Переход на toast из HeroUI

src/frontend/components/wish/card.tsx, src/frontend/components/wishlist/selectModal.tsx
=> [UI] Исправлено закрытие окна карточки

src/frontend/app/providers.tsx, src/frontend/package-lock.json, src/frontend/package.json
=> [UI] Исправлено отображение уведомлений

src/frontend/components/marketIcon.tsx
=> [UI] Добавлены новые иконки магазинов

.github/workflows/go.yml, example.env, src/backend/Dockerfile, src/backend/config/config.go, src/backend/go.mod, src/backend/go.sum, src/backend/main.go, src/backend/service/impl/image.go, src/backend/service/impl/image_test.go
=> [UI] Реализована конвертация изображений в webp

src/frontend/components/user/card.tsx, src/frontend/components/user/status.tsx
=> [UI] Исправлено отображение загрузки пользователя

src/frontend/components/wish/form.tsx, src/frontend/lib/url.ts
=> [UI] Исправлено определение базового URL

src/backend/controller/wishlist.go, src/frontend/components/wish/form.tsx, src/frontend/components/wish/loadByLinkModal.tsx, src/frontend/lib/models/parse.ts, src/frontend/lib/requests/parse.tsx, src/frontend/lib/url.ts
=> [UI] Добавлена загрузка данных из ozon и wildberries

src/frontend/components/wishlist/detail.tsx
=> [UI] Исправлено некорректное добавление желания

src/frontend/components/wish/form.tsx, src/frontend/components/wish/loadByLinkModal.tsx
=> [UI] Добавлена автозагрузка после вставки ссылки

src/frontend/components/wish/form.tsx, src/frontend/lib/models/parse.ts
=> [UI] Добавлена установка валюты при парсинге магазинов

docker-compose.dev.yml, src/backend/controller/user.go
=> [API] Исправлена обработка пустых пробелов

src/frontend/app/layout.tsx, src/frontend/config/site.ts
=> [UI] Исправлен заголовок страницы

src/backend/model/null.go
=> [UI] Исправлен разбор строки для NullString

src/frontend/components/wish/form.tsx, src/frontend/components/wishlist/form.tsx
=> [UI] Доработаны поля ввода описания

src/frontend/components/wish/loadByLinkModal.tsx
=> [UI] Доработано окно автозаполнения

src/frontend/components/wish/fullCard.tsx
=> [UI] Добавлено отображение переноса строк для желания

.github/workflows/release-deploy.yml, .github/workflows/test-deploy.yml, src/frontend/Dockerfile, src/frontend/components/friends/requests.tsx, src/frontend/components/menu.tsx, src/frontend/lib/socket.ts, src/frontend/package-lock.json, src/frontend/package.json
=> [UI] Реализовано обновление счетчика зявок через WS

src/frontend/app/robots.ts
=> [UI] Доработ robots.txt

src/backend/service/impl/wishlist.go
=> [API] Исправлена отправка события в WS при перемещении желания

src/frontend/components/reserved/reservedList.tsx, src/frontend/components/wish/card.tsx, src/frontend/components/wishlist/detail.tsx
=> [UI] Исправлено обновление вишлиста

src/backend/controller/websocket.go, src/backend/service/ws.go
=> [API] Добавлена обработка ping в вебсокете

src/frontend/components/menu.tsx, src/frontend/components/wishlist/detail.tsx, src/frontend/lib/socket.ts, src/frontend/package-lock.json, src/frontend/package.json
=> [UI] Добавлен ping для поддержания соединения

src/backend/db/migrations/000015_add_birthday.down.sql, src/backend/db/migrations/000015_add_birthday.up.sql, src/backend/model/null.go, src/backend/model/user.go, src/backend/repository/impl/user.go, src/backend/service/impl/user.go
=> [API] Добавлены поля для дня рождения

src/frontend/components/settings/profile.tsx, src/frontend/components/wishlist/form.tsx, src/frontend/lib/date.ts, src/frontend/lib/models/user.ts
=> [UI] Добавлено поле для дня рождения

src/frontend/components/user/card.tsx, src/frontend/components/user/status.tsx
=> [UI] Добавлено отображения дня рождения в профиле

src/frontend/app/auth/oauth/[type]/window.tsx
=> [UI] Исправлена обработка OAuth на мобильных устройствах

src/frontend/app/auth/oauth/[type]/page.tsx, src/frontend/app/auth/oauth/[type]/window.tsx, src/frontend/app/auth/register/page.tsx, src/frontend/components/auth/signInForm.tsx, src/frontend/components/login.tsx, src/frontend/components/wishlist/detail.tsx, src/frontend/middleware.ts
=> [UI] Реализовано перенаправление на исходную страницу после авторизации

src/frontend/app/auth/oauth/[type]/layout.tsx, src/frontend/app/auth/reset-password/page.tsx, src/frontend/components/auth/signInForm.tsx
=> [UI] Доработано сохранение ссылка редиректа

src/backend/model/null.go, src/backend/oauth/oauth.go, src/backend/oauth/yandex/yandex.go, src/backend/repository/impl/user.go, src/backend/repository/mocks/UserRepository.go, src/backend/repository/user.go, src/backend/service/impl/user.go, src/backend/service/impl/user_test.go
=> [API] Реализовано заполнения дня рождения из OAuth

src/frontend/components/user/card.tsx, src/frontend/lib/date.ts
=> [UI] Изменен формат отображения дня рождения

src/frontend/lib/date.ts
=> [UI] Исправлено отображения дня рождения

src/backend/controller/wishlist.go
=> [API] Добавлен API для получения доступных парсеров

src/frontend/components/user/card.tsx, src/frontend/components/wishlist/detail.tsx
=> [UI] Переиспользована карточка пользователя на странице вишлиста

src/frontend/app/auth/login/page.tsx, src/frontend/app/auth/oauth/[type]/layout.tsx, src/frontend/app/auth/register/layout.tsx
=> [UI] Исправлены описания страниц регистрации/авторизации

src/frontend/components/wishlist/detail.tsx
=> [UI] Исправлена обработка несуществующего вишлиста

src/frontend/components/wishlist/detail.tsx
=> [UI] Добавлена статистика вишлиста

src/frontend/components/user/card.tsx, src/frontend/components/user/status.tsx, src/frontend/components/wishlist/detail.tsx
=> [UI] Переработана ссылка на профиль пользователя

src/backend/service/impl/wishlist.go, src/backend/service/impl/wishlist_test.go, src/frontend/components/wishlist/detail.tsx
=> [UI] Исправлено отображение элементов заголовка вишлиста

src/frontend/components/filter.tsx, src/frontend/components/wish/filter.tsx, src/frontend/components/wishlist/filter.tsx
=> [UI] Переработан фильтр на странице вишлистов

src/frontend/components/wish/sortingSelector.tsx
=> [UI] Добавлена иконка для селектора сортировки

src/frontend/components/wishlist/detail.tsx
=> [UI] Реализовано сокрытие фильтров при отсутствии желаний

src/frontend/components/filter.tsx
=> [UI] Исправлено применение фильтра при закрытии окна

src/frontend/components/filter.tsx, src/frontend/components/wish/filter.tsx
=> [UI] Исправлены размеры окна фильтра

src/frontend/components/wishlist/detail.tsx, src/frontend/components/wishlist/filter.tsx, src/frontend/lib/compare.ts
=> [UI] Исправлено обновление фильтра при отсутствии изменений

src/frontend/components/wishlist/filter.tsx, src/frontend/components/wishlist/list.tsx
=> [UI] Исправлены отступы в фильтре вишлистов
